# Generated by Django 2.2.9 on 2020-01-29 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='atk_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='result',
            name='def_choice',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='atk_choice', to='RPS.Choice'),
        ),
    ]
