# Generated by Django 2.2.9 on 2020-01-29 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPS', '0002_auto_20200129_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='def_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atk_choice', to='RPS.Choice'),
        ),
    ]
